### ISSUE TITLE
Design registration and login forms

### ISSUE THREAD

**Issue by satishusk** [ProkopovVsevolod/practic-site#1]
API:

Registration: `http://localhost:8001/api/v1/users/register `
```
{
	"name": "example_name",
	"email": "example_email",
	"password": "example_password"
}
```
Authentication: `http://localhost:8001/api/v1/users/login`
```
{
	"email": "example_email",
	"password": "example_password"
}
```

**Comment by ProkopovVsevolod** [comment]
https://www.figma.com/file/eqVW2fAsL1fHkBHH65oo23/E-Commerce-Dashboard-(Community)?type=design&node-id=0-1&mode=design&t=QxrilMNoCUEDG0PS-0

Дизайн главной страницы. Дизайн регистрации и авторизации пропущен
